// Attachment pipeline on real Office/PDF fixtures (generated by python-docx / openpyxl / reportlab).
// No model here: redaction uses the regex layer + a fake name list, the point is extraction and rewriting.
import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { createRequire } from "node:module";
import JSZip from "jszip";
import { docxSegments, docxRewrite, xlsxSegments, xlsxRewrite, pdfSegments, pdfToText, diffReplacements, rewritePieces, outputName } from "../src/files.mjs";

const require = createRequire(import.meta.url);
const { findPII } = require("../src/recognizers.js");
const { createVault } = require("../src/vault.js");
const here = path.dirname(fileURLToPath(import.meta.url));
const fx = (f) => fs.readFileSync(path.join(here, "fixtures", "files", f));

// fake "NER": a few literal names, so the test exercises spans that cross DOCX runs ("Jean " + "Dupont")
const NAMES = ["Jean Dupont", "DUPONT Jean", "LE GOFF Isaac", "Sophie Martin"];
function detect(text) {
  const m = findPII(text).map(x => ({ type: x.type, start: x.start, end: x.end, text: x.text }));
  for (const n of NAMES) { let i = -1; while ((i = text.indexOf(n, i + 1)) !== -1) m.push({ type: "PERSON", start: i, end: i + n.length, text: n }); }
  return m.sort((a, b) => a.start - b.start);
}
function redactAll(segments, vault) {
  const out = {};
  for (const s of segments) { const m = detect(s.text); if (m.length) out[s.id] = vault.redact(s.text, m); }
  return out;
}

test("rewritePieces keeps a placeholder in the first run it touches, later runs shrink", () => {
  const pieces = ["Contrat entre ", "Jean ", "Dupont", ", né le 12/03/1985."];
  const original = pieces.join("");
  const redacted = "Contrat entre {{PERSON_1}}, né le {{DOB_1}}.";
  const reps = diffReplacements(original, redacted);
  assert.deepEqual(reps.map(r => [original.slice(r.start, r.end), r.repl]), [["Jean Dupont", "{{PERSON_1}}"], ["12/03/1985", "{{DOB_1}}"]]);
  assert.deepEqual(rewritePieces(pieces, original, redacted, reps), ["Contrat entre ", "{{PERSON_1}}", "", ", né le {{DOB_1}}."]);
});

test("DOCX: names split across runs, header and table cells are masked; layout XML intact", async () => {
  const doc = await docxSegments(fx("contrat.docx"));
  const vault = createVault();
  const red = redactAll(doc.segments, vault);
  const bytes = await docxRewrite(doc, red);
  const zip = await JSZip.loadAsync(bytes);
  const body = await zip.file("word/document.xml").async("string");
  const header = (await Promise.all(Object.keys(zip.files).filter(n => /^word\/header/.test(n)).map(n => zip.file(n).async("string")))).join("");
  for (const leak of ["Dupont", "DUPONT", "GOFF", "552 100 554 00013", "jean.dupont@example.com", "185057800608491", "1 85 05 78 006 084 91"]) {
    assert.ok(!body.includes(leak), "leaked in body: " + leak);
    assert.ok(!header.includes(leak), "leaked in header: " + leak);
  }
  assert.ok(body.includes("{{PERSON_1}}") && body.includes("{{SIRET_1}}") && body.includes("{{NIR_1}}") && body.includes("{{EMAIL_1}}"));
  assert.ok(/\{\{PERSON_\d+\}\}/.test(header), "header name not masked");
  assert.ok(body.includes("<w:tbl>") && /<w:b\/>/.test(body), "formatting removed");   // bold runs and table survive
  assert.ok(body.includes("Contrat entre "), "surrounding text altered");
});

test("XLSX: shared strings, numeric SIRET cell and inline values are masked; formula untouched", async () => {
  const doc = await xlsxSegments(fx("clients.xlsx"));
  const vault = createVault();
  const red = redactAll(doc.segments, vault);
  const bytes = await xlsxRewrite(doc, red);
  const zip = await JSZip.loadAsync(bytes);
  const ss = zip.file("xl/sharedStrings.xml") ? await zip.file("xl/sharedStrings.xml").async("string") : "";
  const sheet = await zip.file("xl/worksheets/sheet1.xml").async("string");
  for (const leak of ["Jean Dupont", "GOFF", "552 100 554 00013", "FR7630006000011234567890189", "FR76 3000", "jean.dupont@example.com", "isaac@legoff.fr"]) {
    assert.ok(!ss.includes(leak) && !sheet.includes(leak), "leaked: " + leak);
  }
  assert.ok(!sheet.includes("<v>55210055400013</v>"), "numeric SIRET leaked");
  assert.ok(sheet.includes('t="inlineStr"') && sheet.includes("{{SIRET_"), "numeric cell not converted");
  assert.ok(sheet.includes("<f>SUM(E2:E3)</f>"), "formula altered");
  assert.ok(sheet.includes("Montant") && sheet.includes("Total"), "harmless strings altered");
  assert.equal(outputName("clients.xlsx", false), "clients-masqué.xlsx");
});

test("PDF: text layer extracted by line, redacted to .txt; scanned PDF detected", async () => {
  const pdfjs = await import("pdfjs-dist/legacy/build/pdf.mjs");
  const { segments, scanned } = await pdfSegments(new Uint8Array(fx("facture.pdf")), pdfjs);
  assert.equal(scanned, false);
  const vault = createVault();
  const txt = pdfToText(segments, redactAll(segments, vault));
  for (const leak of ["DUPONT", "Dupont", "552 100 554", "06 12 34 56 78", "jean.dupont@example.com", "1 85 05 78 006 084 91", "FR76 3000", "Sophie Martin", "07 98 76 54 32"]) {
    assert.ok(!txt.includes(leak), "leaked: " + leak);
  }
  assert.ok(txt.includes("FAC-2026-0042 du 27/04/2026") && txt.includes("1 250,00 €"), "non-PII altered");
  assert.ok(txt.includes("--- page 2 ---"));
  assert.equal(outputName("facture.pdf", true), "facture-masqué.txt");
  const scan = await pdfSegments(new Uint8Array(fx("scan.pdf")), pdfjs);
  assert.equal(scan.scanned, true);
});

test("XLSX with sharedStrings (Excel-style): rich-text runs and shared cells are masked", async () => {
  const zip = new JSZip();
  zip.file("xl/sharedStrings.xml", '<sst xmlns="x" count="3" uniqueCount="3"><si><t>Jean Dupont</t></si><si><r><rPr><b/></rPr><t xml:space="preserve">LE </t></r><r><t>GOFF Isaac</t></r></si><si><t>Montant</t></si></sst>');
  zip.file("xl/worksheets/sheet1.xml", '<worksheet><sheetData><row r="1"><c r="A1" t="s"><v>0</v></c><c r="B1" t="s"><v>1</v></c><c r="C1" t="s"><v>2</v></c><c r="D1" t="n"><v>55210055400013</v></c></row></sheetData></worksheet>');
  const doc = await xlsxSegments(await zip.generateAsync({ type: "uint8array" }));
  assert.deepEqual(doc.segments.map(s => s.text), ["Jean Dupont", "LE GOFF Isaac", "Montant", "55210055400013"]);
  const vault = createVault();
  const out = await JSZip.loadAsync(await xlsxRewrite(doc, redactAll(doc.segments, vault)));
  const ss = await out.file("xl/sharedStrings.xml").async("string");
  const sheet = await out.file("xl/worksheets/sheet1.xml").async("string");
  assert.ok(ss.includes("<t xml:space=\"preserve\">{{PERSON_1}}</t>") && ss.includes("<t xml:space=\"preserve\">{{PERSON_2}}</t><"), ss);
  assert.ok(ss.includes("<rPr><b/></rPr>") && ss.includes("<t>Montant</t>"), "formatting or harmless string altered");
  assert.ok(sheet.includes('<c r="D1" t="inlineStr"><is><t xml:space="preserve">{{SIRET_1}}</t></is></c>'), sheet);
});
